# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 17a08e0564242b959491d07c9fa5b0cda20dae881ec6a1cfb101ff160b202d02dcd0bb54757cd9e1dcb8b67751fcf8d842516d16a3ff2fcc57e235c44455c109

test:
  secret_key_base: d82f725a36b7731ee2e57ee6514e6488862cc6073a01d469a9457665e76d8ec67544a29f8089de19948357aec788d11a84eefeb3668c7d84cf9a8e31ee40dbb2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
